### PR TITLE
User can create events

### PR DESCRIPTION
**Pull request by jadenbertino**
https://user-images.githubusercontent.com/87284530/219547203-e35cefcb-f58b-460c-adce-797af0ff4cc9.mp4

### CODE REVIEW

**Review by kurtyazdizadeh — APPROVED** [review]
All super cool features so far! I'd say in general to just clean up the UI and make it a little more user friendly. I know the frontend isn't complete, but having things like placeholders or a caption instructing the user how to fill out the form when they submit an invalid input is helpful.

Also, what happens if the user types in military time? ie. 15:33 instead of 3:33pm?

**Comment by jadenbertino** [comment]
Todos:
- [ ] make frontend ui not ugly anymore
- [ ] Allow military time 
- [ ] Guide user through invalid forms
  - [ ] signup
  - [ ] signin
  - [ ] new event
    - [ ] name
    - [ ] notes
    - [ ] date
    - [ ] start time
    - [ ] end time

**Comment by jadenbertino** [comment]
https://user-images.githubusercontent.com/87284530/220256791-5abf783d-9f81-42d4-9e71-949c1615ba75.mp4

https://user-images.githubusercontent.com/87284530/220257142-7b1b7ccb-7d21-4506-a68b-553bdc2cee98.mp4

**Review by kurtyazdizadeh — CHANGES_REQUESTED** [review]
One more issue with the time validation -- If I use military time and say my hours are "53:00" it fast forwards to the next day. 

Can you add some extra validation so that you can't enter a time past "24:00"?

**Review by kurtyazdizadeh — APPROVED** [review]
Approved

**Pull request merged**
